package net.subroh0508.otonashi.vocabularies.schema
import net.subroh0508.otonashi.triples.TripleFacade
import net.subroh0508.otonashi.triples.extensions.get
import net.subroh0508.otonashi.triples.vocabulary.IriVocabulary

/*
 * This file was auto generated by otonashi-vocabularies-generator plugin
 *
 */

val Set<IriVocabulary>.schemaC get() = get(SchemaClass::class)
val TripleFacade.schemaC get() = iri.schemaC

val Set<IriVocabulary>.schemaP get() = get(SchemaProperty::class)
val TripleFacade.schemaP get() = iri.schemaP
