package net.subroh0508.otonashi.vocabularies.schema

import net.subroh0508.otonashi.triples.vocabulary.IriVocabulary

/*
 * This file was auto generated by otonashi-vocabularies-generator plugin
 *
 */

object SchemaClass : IriVocabulary(
    "schema",
    "AMRadioChannel", "APIReference", "AboutPage", "AcceptAction", "Accommodation", "AccountingService", "AchieveAction", "Action", "ActionAccessSpecification", "ActionStatusType",
    "ActivateAction", "AddAction", "AdministrativeArea", "AdultEntertainment", "AggregateOffer", "AggregateRating", "AgreeAction", "Airline", "Airport", "AlignmentObject",
    "AllocateAction", "AmusementPark", "AnimalShelter", "Answer", "Apartment", "ApartmentComplex", "AppendAction", "ApplyAction", "Aquarium", "ArriveAction",
    "ArtGallery", "Article", "AskAction", "AssessAction", "AssignAction", "Attorney", "Audience", "AudioObject", "AuthorizeAction", "AutoBodyShop",
    "AutoDealer", "AutoPartsStore", "AutoRental", "AutoRepair", "AutoWash", "AutomatedTeller", "AutomotiveBusiness", "Bakery", "BankAccount", "BankOrCreditUnion",
    "BarOrPub", "Barcode", "Beach", "BeautySalon", "BedAndBreakfast", "BedDetails", "BedType", "BefriendAction", "BikeStore", "Blog",
    "BlogPosting", "BoardingPolicyType", "BodyOfWater", "Book", "BookFormatType", "BookSeries", "BookStore", "BookmarkAction", "BorrowAction", "BowlingAlley",
    "Brand", "BreadcrumbList", "Brewery", "Bridge", "BroadcastChannel", "BroadcastEvent", "BroadcastFrequencySpecification", "BroadcastService", "BuddhistTemple", "BusReservation",
    "BusStation", "BusStop", "BusTrip", "BusinessAudience", "BusinessEntityType", "BusinessEvent", "BusinessFunction", "BuyAction", "CableOrSatelliteService", "CafeOrCoffeeShop",
    "Campground", "CampingPitch", "Canal", "CancelAction", "Car", "Casino", "CatholicChurch", "Cemetery", "CheckAction", "CheckInAction",
    "CheckOutAction", "CheckoutPage", "ChildCare", "ChildrensEvent", "ChooseAction", "Church", "City", "CityHall", "CivicStructure", "ClaimReview",
    "Clip", "ClothingStore", "Code", "CollectionPage", "CollegeOrUniversity", "ComedyClub", "ComedyEvent", "Comment", "CommentAction", "CommunicateAction",
    "CompoundPriceSpecification", "ComputerLanguage", "ComputerStore", "ConfirmAction", "ConsumeAction", "ContactPage", "ContactPoint", "ContactPointOption", "Continent", "ControlAction",
    "ConvenienceStore", "Conversation", "CookAction", "Corporation", "Country", "Course", "CourseInstance", "Courthouse", "CreateAction", "CreativeWork",
    "CreativeWorkSeason", "CreativeWorkSeries", "CreditCard", "Crematorium", "CurrencyConversionService", "DanceEvent", "DanceGroup", "DataCatalog", "DataDownload", "DataFeed",
    "DataFeedItem", "DataType", "Dataset", "DatedMoneySpecification", "DayOfWeek", "DaySpa", "DeactivateAction", "DefenceEstablishment", "DeleteAction", "DeliveryChargeSpecification",
    "DeliveryEvent", "DeliveryMethod", "Demand", "Dentist", "DepartAction", "DepartmentStore", "DepositAccount", "DigitalDocument", "DigitalDocumentPermission", "DigitalDocumentPermissionType",
    "DisagreeAction", "DiscoverAction", "DiscussionForumPosting", "DislikeAction", "Distance", "Distillery", "DonateAction", "DownloadAction", "DrawAction", "DrinkAction",
    "DriveWheelConfigurationValue", "DryCleaningOrLaundry", "Duration", "EatAction", "EducationEvent", "EducationalAudience", "EducationalOrganization", "Electrician", "ElectronicsStore", "ElementarySchool",
    "EmailMessage", "Embassy", "EmergencyService", "EmployeeRole", "EmployerAggregateRating", "EmploymentAgency", "EndorseAction", "EndorsementRating", "Energy", "EngineSpecification",
    "EntertainmentBusiness", "EntryPoint", "Enumeration", "Episode", "Event", "EventReservation", "EventStatusType", "EventVenue", "ExerciseAction", "ExerciseGym",
    "ExhibitionEvent", "FAQPage", "FMRadioChannel", "FastFoodRestaurant", "Festival", "FilmAction", "FinancialProduct", "FinancialService", "FindAction", "FireStation",
    "Flight", "FlightReservation", "Float", "Florist", "FollowAction", "FoodEstablishment", "FoodEstablishmentReservation", "FoodEvent", "FoodService", "FurnitureStore",
    "Game", "GamePlayMode", "GameServer", "GameServerStatus", "GardenStore", "GasStation", "GatedResidenceCommunity", "GenderType", "GeneralContractor", "GeoCircle",
    "GeoCoordinates", "GeoShape", "GiveAction", "GolfCourse", "GovernmentBuilding", "GovernmentOffice", "GovernmentOrganization", "GovernmentPermit", "GovernmentService", "GroceryStore",
    "HVACBusiness", "HairSalon", "HardwareStore", "HealthAndBeautyBusiness", "HealthClub", "HighSchool", "HinduTemple", "HobbyShop", "HomeAndConstructionBusiness", "HomeGoodsStore",
    "Hospital", "Hostel", "Hotel", "HotelRoom", "House", "HousePainter", "HowTo", "HowToDirection", "HowToItem", "HowToSection",
    "HowToStep", "HowToSupply", "HowToTip", "HowToTool", "IceCreamShop", "IgnoreAction", "ImageGallery", "ImageObject", "IndividualProduct", "InformAction",
    "InsertAction", "InstallAction", "InsuranceAgency", "Intangible", "Integer", "InteractAction", "InteractionCounter", "InternetCafe", "InvestmentOrDeposit", "InviteAction",
    "Invoice", "ItemAvailability", "ItemList", "ItemListOrderType", "ItemPage", "JewelryStore", "JobPosting", "JoinAction", "LakeBodyOfWater", "Landform",
    "LandmarksOrHistoricalBuildings", "Language", "LeaveAction", "LegalService", "LegislativeBuilding", "LendAction", "Library", "LikeAction", "LiquorStore", "ListItem",
    "ListenAction", "LiteraryEvent", "LiveBlogPosting", "LoanOrCredit", "LocalBusiness", "LocationFeatureSpecification", "LockerDelivery", "Locksmith", "LodgingBusiness", "LodgingReservation",
    "LoseAction", "Map", "MapCategoryType", "MarryAction", "Mass", "MediaObject", "MediaSubscription", "MedicalOrganization", "MeetingRoom", "MensClothingStore",
    "Menu", "MenuItem", "MenuSection", "Message", "MiddleSchool", "MobileApplication", "MobilePhoneStore", "MonetaryAmount", "MonetaryAmountDistribution", "Mosque",
    "Motel", "MotorcycleDealer", "MotorcycleRepair", "Mountain", "MoveAction", "Movie", "MovieClip", "MovieRentalStore", "MovieSeries", "MovieTheater",
    "MovingCompany", "Museum", "MusicAlbum", "MusicAlbumProductionType", "MusicAlbumReleaseType", "MusicComposition", "MusicEvent", "MusicGroup", "MusicPlaylist", "MusicRecording",
    "MusicRelease", "MusicReleaseFormatType", "MusicStore", "MusicVenue", "MusicVideoObject", "NGO", "NailSalon", "NewsArticle", "NightClub", "Notary",
    "NoteDigitalDocument", "NutritionInformation", "Occupation", "OceanBodyOfWater", "Offer", "OfferCatalog", "OfferItemCondition", "OfficeEquipmentStore", "OnDemandEvent", "OpeningHoursSpecification",
    "Order", "OrderAction", "OrderItem", "OrderStatus", "Organization", "OrganizationRole", "OrganizeAction", "OutletStore", "OwnershipInfo", "PaintAction",
    "Painting", "ParcelDelivery", "ParcelService", "ParentAudience", "Park", "ParkingFacility", "PawnShop", "PayAction", "PaymentCard", "PaymentChargeSpecification",
    "PaymentMethod", "PaymentService", "PaymentStatusType", "PeopleAudience", "PerformAction", "PerformanceRole", "PerformingArtsTheater", "PerformingGroup", "Periodical", "Permit",
    "Person", "PetStore", "Pharmacy", "Photograph", "PhotographAction", "Physician", "Place", "PlaceOfWorship", "PlanAction", "PlayAction",
    "Playground", "Plumber", "PoliceStation", "Pond", "PostOffice", "PostalAddress", "PreOrderAction", "PrependAction", "Preschool", "PresentationDigitalDocument",
    "PriceSpecification", "Product", "ProductModel", "ProfessionalService", "ProfilePage", "ProgramMembership", "PropertyValue", "PropertyValueSpecification", "PublicSwimmingPool", "PublicationEvent",
    "PublicationIssue", "PublicationVolume", "QAPage", "QualitativeValue", "QuantitativeValue", "QuantitativeValueDistribution", "Quantity", "Question", "QuoteAction", "RVPark",
    "RadioChannel", "RadioClip", "RadioEpisode", "RadioSeason", "RadioSeries", "RadioStation", "Rating", "ReactAction", "ReadAction", "RealEstateAgent",
    "ReceiveAction", "Recipe", "RecyclingCenter", "RegisterAction", "RejectAction", "RentAction", "RentalCarReservation", "ReplaceAction", "ReplyAction", "Report",
    "Reservation", "ReservationPackage", "ReservationStatusType", "ReserveAction", "Reservoir", "Residence", "Resort", "Restaurant", "RestrictedDiet", "ResumeAction",
    "ReturnAction", "Review", "ReviewAction", "RiverBodyOfWater", "Role", "RoofingContractor", "Room", "RsvpAction", "RsvpResponseType", "SaleEvent",
    "ScheduleAction", "ScholarlyArticle", "School", "ScreeningEvent", "Sculpture", "SeaBodyOfWater", "SearchAction", "SearchResultsPage", "Season", "Seat",
    "SelfStorage", "SellAction", "SendAction", "Series", "Service", "ServiceChannel", "ShareAction", "ShoeStore", "ShoppingCenter", "SingleFamilyResidence",
    "SiteNavigationElement", "SkiResort", "SocialEvent", "SocialMediaPosting", "SoftwareApplication", "SoftwareSourceCode", "SomeProducts", "SpeakableSpecification", "Specialty", "SportingGoodsStore",
    "SportsActivityLocation", "SportsClub", "SportsEvent", "SportsOrganization", "SportsTeam", "SpreadsheetDigitalDocument", "StadiumOrArena", "State", "SteeringPositionValue", "Store",
    "StructuredValue", "SubscribeAction", "SubwayStation", "Suite", "SuspendAction", "Synagogue", "TVClip", "TVEpisode", "TVSeason", "TVSeries",
    "Table", "TakeAction", "TattooParlor", "Taxi", "TaxiReservation", "TaxiService", "TaxiStand", "TechArticle", "TelevisionChannel", "TelevisionStation",
    "TennisComplex", "TextDigitalDocument", "TheaterEvent", "TheaterGroup", "Thing", "Ticket", "TieAction", "TipAction", "TireShop", "TouristAttraction",
    "TouristInformationCenter", "ToyStore", "TrackAction", "TradeAction", "TrainReservation", "TrainStation", "TrainTrip", "TransferAction", "TravelAction", "TravelAgency",
    "Trip", "TypeAndQuantityNode", "URL", "UnRegisterAction", "UnitPriceSpecification", "UpdateAction", "UseAction", "UserBlocks", "UserCheckins", "UserComments",
    "UserDownloads", "UserInteraction", "UserLikes", "UserPageVisits", "UserPlays", "UserPlusOnes", "UserTweets", "Vehicle", "VideoGallery", "VideoGame",
    "VideoGameClip", "VideoGameSeries", "VideoObject", "ViewAction", "VisualArtsEvent", "VisualArtwork", "Volcano", "VoteAction", "WPAdBlock", "WPFooter",
    "WPHeader", "WPSideBar", "WantAction", "WarrantyPromise", "WarrantyScope", "WatchAction", "Waterfall", "WearAction", "WebApplication", "WebPage",
    "WebPageElement", "WebSite", "WholesaleStore", "WinAction", "Winery", "WorkersUnion", "WriteAction", "Zoo"
) {
    val aMRadioChannel by iriStore
    val aPIReference by iriStore
    val aboutPage by iriStore
    val acceptAction by iriStore
    val accommodation by iriStore
    val accountingService by iriStore
    val achieveAction by iriStore
    val action by iriStore
    val actionAccessSpecification by iriStore
    val actionStatusType by iriStore
    val activateAction by iriStore
    val addAction by iriStore
    val administrativeArea by iriStore
    val adultEntertainment by iriStore
    val aggregateOffer by iriStore
    val aggregateRating by iriStore
    val agreeAction by iriStore
    val airline by iriStore
    val airport by iriStore
    val alignmentObject by iriStore
    val allocateAction by iriStore
    val amusementPark by iriStore
    val animalShelter by iriStore
    val answer by iriStore
    val apartment by iriStore
    val apartmentComplex by iriStore
    val appendAction by iriStore
    val applyAction by iriStore
    val aquarium by iriStore
    val arriveAction by iriStore
    val artGallery by iriStore
    val article by iriStore
    val askAction by iriStore
    val assessAction by iriStore
    val assignAction by iriStore
    val attorney by iriStore
    val audience by iriStore
    val audioObject by iriStore
    val authorizeAction by iriStore
    val autoBodyShop by iriStore
    val autoDealer by iriStore
    val autoPartsStore by iriStore
    val autoRental by iriStore
    val autoRepair by iriStore
    val autoWash by iriStore
    val automatedTeller by iriStore
    val automotiveBusiness by iriStore
    val bakery by iriStore
    val bankAccount by iriStore
    val bankOrCreditUnion by iriStore
    val barOrPub by iriStore
    val barcode by iriStore
    val beach by iriStore
    val beautySalon by iriStore
    val bedAndBreakfast by iriStore
    val bedDetails by iriStore
    val bedType by iriStore
    val befriendAction by iriStore
    val bikeStore by iriStore
    val blog by iriStore
    val blogPosting by iriStore
    val boardingPolicyType by iriStore
    val bodyOfWater by iriStore
    val book by iriStore
    val bookFormatType by iriStore
    val bookSeries by iriStore
    val bookStore by iriStore
    val bookmarkAction by iriStore
    val borrowAction by iriStore
    val bowlingAlley by iriStore
    val brand by iriStore
    val breadcrumbList by iriStore
    val brewery by iriStore
    val bridge by iriStore
    val broadcastChannel by iriStore
    val broadcastEvent by iriStore
    val broadcastFrequencySpecification by iriStore
    val broadcastService by iriStore
    val buddhistTemple by iriStore
    val busReservation by iriStore
    val busStation by iriStore
    val busStop by iriStore
    val busTrip by iriStore
    val businessAudience by iriStore
    val businessEntityType by iriStore
    val businessEvent by iriStore
    val businessFunction by iriStore
    val buyAction by iriStore
    val cableOrSatelliteService by iriStore
    val cafeOrCoffeeShop by iriStore
    val campground by iriStore
    val campingPitch by iriStore
    val canal by iriStore
    val cancelAction by iriStore
    val car by iriStore
    val casino by iriStore
    val catholicChurch by iriStore
    val cemetery by iriStore
    val checkAction by iriStore
    val checkInAction by iriStore
    val checkOutAction by iriStore
    val checkoutPage by iriStore
    val childCare by iriStore
    val childrensEvent by iriStore
    val chooseAction by iriStore
    val church by iriStore
    val city by iriStore
    val cityHall by iriStore
    val civicStructure by iriStore
    val claimReview by iriStore
    val clip by iriStore
    val clothingStore by iriStore
    val code by iriStore
    val collectionPage by iriStore
    val collegeOrUniversity by iriStore
    val comedyClub by iriStore
    val comedyEvent by iriStore
    val comment by iriStore
    val commentAction by iriStore
    val communicateAction by iriStore
    val compoundPriceSpecification by iriStore
    val computerLanguage by iriStore
    val computerStore by iriStore
    val confirmAction by iriStore
    val consumeAction by iriStore
    val contactPage by iriStore
    val contactPoint by iriStore
    val contactPointOption by iriStore
    val continent by iriStore
    val controlAction by iriStore
    val convenienceStore by iriStore
    val conversation by iriStore
    val cookAction by iriStore
    val corporation by iriStore
    val country by iriStore
    val course by iriStore
    val courseInstance by iriStore
    val courthouse by iriStore
    val createAction by iriStore
    val creativeWork by iriStore
    val creativeWorkSeason by iriStore
    val creativeWorkSeries by iriStore
    val creditCard by iriStore
    val crematorium by iriStore
    val currencyConversionService by iriStore
    val danceEvent by iriStore
    val danceGroup by iriStore
    val dataCatalog by iriStore
    val dataDownload by iriStore
    val dataFeed by iriStore
    val dataFeedItem by iriStore
    val dataType by iriStore
    val dataset by iriStore
    val datedMoneySpecification by iriStore
    val dayOfWeek by iriStore
    val daySpa by iriStore
    val deactivateAction by iriStore
    val defenceEstablishment by iriStore
    val deleteAction by iriStore
    val deliveryChargeSpecification by iriStore
    val deliveryEvent by iriStore
    val deliveryMethod by iriStore
    val demand by iriStore
    val dentist by iriStore
    val departAction by iriStore
    val departmentStore by iriStore
    val depositAccount by iriStore
    val digitalDocument by iriStore
    val digitalDocumentPermission by iriStore
    val digitalDocumentPermissionType by iriStore
    val disagreeAction by iriStore
    val discoverAction by iriStore
    val discussionForumPosting by iriStore
    val dislikeAction by iriStore
    val distance by iriStore
    val distillery by iriStore
    val donateAction by iriStore
    val downloadAction by iriStore
    val drawAction by iriStore
    val drinkAction by iriStore
    val driveWheelConfigurationValue by iriStore
    val dryCleaningOrLaundry by iriStore
    val duration by iriStore
    val eatAction by iriStore
    val educationEvent by iriStore
    val educationalAudience by iriStore
    val educationalOrganization by iriStore
    val electrician by iriStore
    val electronicsStore by iriStore
    val elementarySchool by iriStore
    val emailMessage by iriStore
    val embassy by iriStore
    val emergencyService by iriStore
    val employeeRole by iriStore
    val employerAggregateRating by iriStore
    val employmentAgency by iriStore
    val endorseAction by iriStore
    val endorsementRating by iriStore
    val energy by iriStore
    val engineSpecification by iriStore
    val entertainmentBusiness by iriStore
    val entryPoint by iriStore
    val enumeration by iriStore
    val episode by iriStore
    val event by iriStore
    val eventReservation by iriStore
    val eventStatusType by iriStore
    val eventVenue by iriStore
    val exerciseAction by iriStore
    val exerciseGym by iriStore
    val exhibitionEvent by iriStore
    val fAQPage by iriStore
    val fMRadioChannel by iriStore
    val fastFoodRestaurant by iriStore
    val festival by iriStore
    val filmAction by iriStore
    val financialProduct by iriStore
    val financialService by iriStore
    val findAction by iriStore
    val fireStation by iriStore
    val flight by iriStore
    val flightReservation by iriStore
    val float by iriStore
    val florist by iriStore
    val followAction by iriStore
    val foodEstablishment by iriStore
    val foodEstablishmentReservation by iriStore
    val foodEvent by iriStore
    val foodService by iriStore
    val furnitureStore by iriStore
    val game by iriStore
    val gamePlayMode by iriStore
    val gameServer by iriStore
    val gameServerStatus by iriStore
    val gardenStore by iriStore
    val gasStation by iriStore
    val gatedResidenceCommunity by iriStore
    val genderType by iriStore
    val generalContractor by iriStore
    val geoCircle by iriStore
    val geoCoordinates by iriStore
    val geoShape by iriStore
    val giveAction by iriStore
    val golfCourse by iriStore
    val governmentBuilding by iriStore
    val governmentOffice by iriStore
    val governmentOrganization by iriStore
    val governmentPermit by iriStore
    val governmentService by iriStore
    val groceryStore by iriStore
    val hVACBusiness by iriStore
    val hairSalon by iriStore
    val hardwareStore by iriStore
    val healthAndBeautyBusiness by iriStore
    val healthClub by iriStore
    val highSchool by iriStore
    val hinduTemple by iriStore
    val hobbyShop by iriStore
    val homeAndConstructionBusiness by iriStore
    val homeGoodsStore by iriStore
    val hospital by iriStore
    val hostel by iriStore
    val hotel by iriStore
    val hotelRoom by iriStore
    val house by iriStore
    val housePainter by iriStore
    val howTo by iriStore
    val howToDirection by iriStore
    val howToItem by iriStore
    val howToSection by iriStore
    val howToStep by iriStore
    val howToSupply by iriStore
    val howToTip by iriStore
    val howToTool by iriStore
    val iceCreamShop by iriStore
    val ignoreAction by iriStore
    val imageGallery by iriStore
    val imageObject by iriStore
    val individualProduct by iriStore
    val informAction by iriStore
    val insertAction by iriStore
    val installAction by iriStore
    val insuranceAgency by iriStore
    val intangible by iriStore
    val integer by iriStore
    val interactAction by iriStore
    val interactionCounter by iriStore
    val internetCafe by iriStore
    val investmentOrDeposit by iriStore
    val inviteAction by iriStore
    val invoice by iriStore
    val itemAvailability by iriStore
    val itemList by iriStore
    val itemListOrderType by iriStore
    val itemPage by iriStore
    val jewelryStore by iriStore
    val jobPosting by iriStore
    val joinAction by iriStore
    val lakeBodyOfWater by iriStore
    val landform by iriStore
    val landmarksOrHistoricalBuildings by iriStore
    val language by iriStore
    val leaveAction by iriStore
    val legalService by iriStore
    val legislativeBuilding by iriStore
    val lendAction by iriStore
    val library by iriStore
    val likeAction by iriStore
    val liquorStore by iriStore
    val listItem by iriStore
    val listenAction by iriStore
    val literaryEvent by iriStore
    val liveBlogPosting by iriStore
    val loanOrCredit by iriStore
    val localBusiness by iriStore
    val locationFeatureSpecification by iriStore
    val lockerDelivery by iriStore
    val locksmith by iriStore
    val lodgingBusiness by iriStore
    val lodgingReservation by iriStore
    val loseAction by iriStore
    val map by iriStore
    val mapCategoryType by iriStore
    val marryAction by iriStore
    val mass by iriStore
    val mediaObject by iriStore
    val mediaSubscription by iriStore
    val medicalOrganization by iriStore
    val meetingRoom by iriStore
    val mensClothingStore by iriStore
    val menu by iriStore
    val menuItem by iriStore
    val menuSection by iriStore
    val message by iriStore
    val middleSchool by iriStore
    val mobileApplication by iriStore
    val mobilePhoneStore by iriStore
    val monetaryAmount by iriStore
    val monetaryAmountDistribution by iriStore
    val mosque by iriStore
    val motel by iriStore
    val motorcycleDealer by iriStore
    val motorcycleRepair by iriStore
    val mountain by iriStore
    val moveAction by iriStore
    val movie by iriStore
    val movieClip by iriStore
    val movieRentalStore by iriStore
    val movieSeries by iriStore
    val movieTheater by iriStore
    val movingCompany by iriStore
    val museum by iriStore
    val musicAlbum by iriStore
    val musicAlbumProductionType by iriStore
    val musicAlbumReleaseType by iriStore
    val musicComposition by iriStore
    val musicEvent by iriStore
    val musicGroup by iriStore
    val musicPlaylist by iriStore
    val musicRecording by iriStore
    val musicRelease by iriStore
    val musicReleaseFormatType by iriStore
    val musicStore by iriStore
    val musicVenue by iriStore
    val musicVideoObject by iriStore
    val nGO by iriStore
    val nailSalon by iriStore
    val newsArticle by iriStore
    val nightClub by iriStore
    val notary by iriStore
    val noteDigitalDocument by iriStore
    val nutritionInformation by iriStore
    val occupation by iriStore
    val oceanBodyOfWater by iriStore
    val offer by iriStore
    val offerCatalog by iriStore
    val offerItemCondition by iriStore
    val officeEquipmentStore by iriStore
    val onDemandEvent by iriStore
    val openingHoursSpecification by iriStore
    val order by iriStore
    val orderAction by iriStore
    val orderItem by iriStore
    val orderStatus by iriStore
    val organization by iriStore
    val organizationRole by iriStore
    val organizeAction by iriStore
    val outletStore by iriStore
    val ownershipInfo by iriStore
    val paintAction by iriStore
    val painting by iriStore
    val parcelDelivery by iriStore
    val parcelService by iriStore
    val parentAudience by iriStore
    val park by iriStore
    val parkingFacility by iriStore
    val pawnShop by iriStore
    val payAction by iriStore
    val paymentCard by iriStore
    val paymentChargeSpecification by iriStore
    val paymentMethod by iriStore
    val paymentService by iriStore
    val paymentStatusType by iriStore
    val peopleAudience by iriStore
    val performAction by iriStore
    val performanceRole by iriStore
    val performingArtsTheater by iriStore
    val performingGroup by iriStore
    val periodical by iriStore
    val permit by iriStore
    val person by iriStore
    val petStore by iriStore
    val pharmacy by iriStore
    val photograph by iriStore
    val photographAction by iriStore
    val physician by iriStore
    val place by iriStore
    val placeOfWorship by iriStore
    val planAction by iriStore
    val playAction by iriStore
    val playground by iriStore
    val plumber by iriStore
    val policeStation by iriStore
    val pond by iriStore
    val postOffice by iriStore
    val postalAddress by iriStore
    val preOrderAction by iriStore
    val prependAction by iriStore
    val preschool by iriStore
    val presentationDigitalDocument by iriStore
    val priceSpecification by iriStore
    val product by iriStore
    val productModel by iriStore
    val professionalService by iriStore
    val profilePage by iriStore
    val programMembership by iriStore
    val propertyValue by iriStore
    val propertyValueSpecification by iriStore
    val publicSwimmingPool by iriStore
    val publicationEvent by iriStore
    val publicationIssue by iriStore
    val publicationVolume by iriStore
    val qAPage by iriStore
    val qualitativeValue by iriStore
    val quantitativeValue by iriStore
    val quantitativeValueDistribution by iriStore
    val quantity by iriStore
    val question by iriStore
    val quoteAction by iriStore
    val rVPark by iriStore
    val radioChannel by iriStore
    val radioClip by iriStore
    val radioEpisode by iriStore
    val radioSeason by iriStore
    val radioSeries by iriStore
    val radioStation by iriStore
    val rating by iriStore
    val reactAction by iriStore
    val readAction by iriStore
    val realEstateAgent by iriStore
    val receiveAction by iriStore
    val recipe by iriStore
    val recyclingCenter by iriStore
    val registerAction by iriStore
    val rejectAction by iriStore
    val rentAction by iriStore
    val rentalCarReservation by iriStore
    val replaceAction by iriStore
    val replyAction by iriStore
    val report by iriStore
    val reservation by iriStore
    val reservationPackage by iriStore
    val reservationStatusType by iriStore
    val reserveAction by iriStore
    val reservoir by iriStore
    val residence by iriStore
    val resort by iriStore
    val restaurant by iriStore
    val restrictedDiet by iriStore
    val resumeAction by iriStore
    val returnAction by iriStore
    val review by iriStore
    val reviewAction by iriStore
    val riverBodyOfWater by iriStore
    val role by iriStore
    val roofingContractor by iriStore
    val room by iriStore
    val rsvpAction by iriStore
    val rsvpResponseType by iriStore
    val saleEvent by iriStore
    val scheduleAction by iriStore
    val scholarlyArticle by iriStore
    val school by iriStore
    val screeningEvent by iriStore
    val sculpture by iriStore
    val seaBodyOfWater by iriStore
    val searchAction by iriStore
    val searchResultsPage by iriStore
    val season by iriStore
    val seat by iriStore
    val selfStorage by iriStore
    val sellAction by iriStore
    val sendAction by iriStore
    val series by iriStore
    val service by iriStore
    val serviceChannel by iriStore
    val shareAction by iriStore
    val shoeStore by iriStore
    val shoppingCenter by iriStore
    val singleFamilyResidence by iriStore
    val siteNavigationElement by iriStore
    val skiResort by iriStore
    val socialEvent by iriStore
    val socialMediaPosting by iriStore
    val softwareApplication by iriStore
    val softwareSourceCode by iriStore
    val someProducts by iriStore
    val speakableSpecification by iriStore
    val specialty by iriStore
    val sportingGoodsStore by iriStore
    val sportsActivityLocation by iriStore
    val sportsClub by iriStore
    val sportsEvent by iriStore
    val sportsOrganization by iriStore
    val sportsTeam by iriStore
    val spreadsheetDigitalDocument by iriStore
    val stadiumOrArena by iriStore
    val state by iriStore
    val steeringPositionValue by iriStore
    val store by iriStore
    val structuredValue by iriStore
    val subscribeAction by iriStore
    val subwayStation by iriStore
    val suite by iriStore
    val suspendAction by iriStore
    val synagogue by iriStore
    val tVClip by iriStore
    val tVEpisode by iriStore
    val tVSeason by iriStore
    val tVSeries by iriStore
    val table by iriStore
    val takeAction by iriStore
    val tattooParlor by iriStore
    val taxi by iriStore
    val taxiReservation by iriStore
    val taxiService by iriStore
    val taxiStand by iriStore
    val techArticle by iriStore
    val televisionChannel by iriStore
    val televisionStation by iriStore
    val tennisComplex by iriStore
    val textDigitalDocument by iriStore
    val theaterEvent by iriStore
    val theaterGroup by iriStore
    val thing by iriStore
    val ticket by iriStore
    val tieAction by iriStore
    val tipAction by iriStore
    val tireShop by iriStore
    val touristAttraction by iriStore
    val touristInformationCenter by iriStore
    val toyStore by iriStore
    val trackAction by iriStore
    val tradeAction by iriStore
    val trainReservation by iriStore
    val trainStation by iriStore
    val trainTrip by iriStore
    val transferAction by iriStore
    val travelAction by iriStore
    val travelAgency by iriStore
    val trip by iriStore
    val typeAndQuantityNode by iriStore
    val uRL by iriStore
    val unRegisterAction by iriStore
    val unitPriceSpecification by iriStore
    val updateAction by iriStore
    val useAction by iriStore
    val userBlocks by iriStore
    val userCheckins by iriStore
    val userComments by iriStore
    val userDownloads by iriStore
    val userInteraction by iriStore
    val userLikes by iriStore
    val userPageVisits by iriStore
    val userPlays by iriStore
    val userPlusOnes by iriStore
    val userTweets by iriStore
    val vehicle by iriStore
    val videoGallery by iriStore
    val videoGame by iriStore
    val videoGameClip by iriStore
    val videoGameSeries by iriStore
    val videoObject by iriStore
    val viewAction by iriStore
    val visualArtsEvent by iriStore
    val visualArtwork by iriStore
    val volcano by iriStore
    val voteAction by iriStore
    val wPAdBlock by iriStore
    val wPFooter by iriStore
    val wPHeader by iriStore
    val wPSideBar by iriStore
    val wantAction by iriStore
    val warrantyPromise by iriStore
    val warrantyScope by iriStore
    val watchAction by iriStore
    val waterfall by iriStore
    val wearAction by iriStore
    val webApplication by iriStore
    val webPage by iriStore
    val webPageElement by iriStore
    val webSite by iriStore
    val wholesaleStore by iriStore
    val winAction by iriStore
    val winery by iriStore
    val workersUnion by iriStore
    val writeAction by iriStore
    val zoo by iriStore
}
