package net.subroh0508.otonashi.vocabularies.schema

import net.subroh0508.otonashi.triples.Prefix

/*
 * This file was auto generated by otonashi-vocabularies-generator plugin
 *
 */

enum class SchemaPrefix(
    override val prefix: String,
    override val iri: String
) : Prefix {
    SCHEMA("schema", "<http://schema.org/>");

    override fun toString() = "PREFIX $prefix: $iri"
}
