package net.subroh0508.otonashi.vocabularies.schema

import net.subroh0508.otonashi.triples.vocabulary.IriVocabulary

/*
 * This file was auto generated by otonashi-vocabularies-generator plugin
 *
 */

object SchemaProperty : IriVocabulary(
    "schema",
    "about", "acceptedAnswer", "acceptedOffer", "acceptedPaymentMethod", "acceptsReservations", "accessCode", "accessMode", "accessModeSufficient", "accessibilityAPI", "accessibilityControl",
    "accessibilityFeature", "accessibilityHazard", "accessibilitySummary", "accountId", "accountablePerson", "acquiredFrom", "actionAccessibilityRequirement", "actionApplication", "actionOption", "actionPlatform",
    "actionStatus", "actor", "actors", "addOn", "additionalName", "additionalNumberOfGuests", "additionalProperty", "additionalType", "address", "addressCountry",
    "addressLocality", "addressRegion", "advanceBookingRequirement", "affiliation", "afterMedia", "agent", "aggregateRating", "aircraft", "album", "albumProductionType",
    "albumRelease", "albumReleaseType", "albums", "alignmentType", "alternateName", "alternativeHeadline", "alumni", "alumniOf", "amenityFeature", "amount",
    "amountOfThisGood", "annualPercentageRate", "answerCount", "application", "applicationCategory", "applicationSubCategory", "applicationSuite", "appliesToDeliveryMethod", "appliesToPaymentMethod", "area",
    "areaServed", "arrivalAirport", "arrivalBusStop", "arrivalGate", "arrivalPlatform", "arrivalStation", "arrivalTerminal", "arrivalTime", "artEdition", "artMedium",
    "artform", "articleBody", "articleSection", "artworkSurface", "assembly", "assemblyVersion", "associatedArticle", "associatedMedia", "athlete", "attendee",
    "attendees", "audience", "audienceType", "audio", "authenticator", "author", "availability", "availabilityEnds", "availabilityStarts", "availableAtOrFrom",
    "availableChannel", "availableDeliveryMethod", "availableFrom", "availableLanguage", "availableOnDevice", "availableThrough", "award", "awards", "awayTeam", "baseSalary",
    "bccRecipient", "bed", "beforeMedia", "benefits", "bestRating", "billingAddress", "billingIncrement", "billingPeriod", "birthDate", "birthPlace",
    "bitrate", "blogPost", "blogPosts", "boardingGroup", "boardingPolicy", "bookEdition", "bookFormat", "bookingAgent", "bookingTime", "borrower",
    "box", "branchCode", "branchOf", "brand", "breadcrumb", "broadcastAffiliateOf", "broadcastChannelId", "broadcastDisplayName", "broadcastFrequency", "broadcastFrequencyValue",
    "broadcastOfEvent", "broadcastServiceTier", "broadcastTimezone", "broadcaster", "broker", "browserRequirements", "busName", "busNumber", "businessFunction", "buyer",
    "byArtist", "calories", "candidate", "caption", "carbohydrateContent", "cargoVolume", "carrier", "carrierRequirements", "catalog", "catalogNumber",
    "category", "ccRecipient", "character", "characterAttribute", "characterName", "cheatCode", "checkinTime", "checkoutTime", "childMaxAge", "childMinAge",
    "children", "cholesterolContent", "circle", "citation", "claimReviewed", "clipNumber", "closes", "coach", "codeRepository", "codeSampleType",
    "colleague", "colleagues", "collection", "color", "comment", "commentCount", "commentText", "commentTime", "competitor", "composer",
    "confirmationNumber", "contactOption", "contactPoint", "contactPoints", "contactType", "containedIn", "containedInPlace", "containsPlace", "containsSeason", "contentLocation",
    "contentRating", "contentSize", "contentType", "contentUrl", "contributor", "cookTime", "cookingMethod", "copyrightHolder", "copyrightYear", "countriesNotSupported",
    "countriesSupported", "countryOfOrigin", "course", "courseCode", "courseMode", "coursePrerequisites", "coverageEndTime", "coverageStartTime", "creator", "creditedTo",
    "cssSelector", "currenciesAccepted", "currency", "customer", "dataFeedElement", "dataset", "datasetTimeInterval", "dateCreated", "dateDeleted", "dateIssued",
    "dateModified", "datePosted", "datePublished", "dateRead", "dateReceived", "dateSent", "dateVehicleFirstRegistered", "dateline", "dayOfWeek", "deathDate",
    "deathPlace", "defaultValue", "deliveryAddress", "deliveryLeadTime", "deliveryMethod", "deliveryStatus", "department", "departureAirport", "departureBusStop", "departureGate",
    "departurePlatform", "departureStation", "departureTerminal", "departureTime", "dependencies", "depth", "description", "device", "director", "directors",
    "disambiguatingDescription", "discount", "discountCode", "discountCurrency", "discusses", "discussionUrl", "dissolutionDate", "distance", "distribution", "doorTime",
    "downloadUrl", "downvoteCount", "driveWheelConfiguration", "dropoffLocation", "dropoffTime", "duns", "duration", "durationOfWarranty", "duringMedia", "editor",
    "educationalAlignment", "educationalFramework", "educationalRole", "educationalUse", "elevation", "eligibleCustomerType", "eligibleDuration", "eligibleQuantity", "eligibleRegion", "eligibleTransactionVolume",
    "email", "embedUrl", "employee", "employees", "employmentType", "encodesCreativeWork", "encoding", "encodingFormat", "encodingType", "encodings",
    "endDate", "endTime", "endorsee", "entertainmentBusiness", "episode", "episodeNumber", "episodes", "equal", "error", "estimatedCost",
    "estimatedFlightDuration", "estimatedSalary", "event", "eventStatus", "events", "exampleOfWork", "executableLibraryName", "exerciseCourse", "exifData", "expectedArrivalFrom",
    "expectedArrivalUntil", "expectsAcceptanceOf", "experienceRequirements", "expires", "familyName", "fatContent", "faxNumber", "featureList", "feesAndCommissionsSpecification", "fiberContent",
    "fileFormat", "fileSize", "firstPerformance", "flightDistance", "flightNumber", "floorSize", "followee", "follows", "foodEstablishment", "foodEvent",
    "founder", "founders", "foundingDate", "foundingLocation", "free", "fromLocation", "fuelConsumption", "fuelEfficiency", "fuelType", "funder",
    "game", "gameItem", "gameLocation", "gamePlatform", "gameServer", "gameTip", "gender", "genre", "geo", "geoContains",
    "geoCoveredBy", "geoCovers", "geoCrosses", "geoDisjoint", "geoEquals", "geoIntersects", "geoMidpoint", "geoOverlaps", "geoRadius", "geoTouches",
    "geoWithin", "geographicArea", "givenName", "globalLocationNumber", "grantee", "greater", "greaterOrEqual", "gtin12", "gtin13", "gtin14",
    "gtin8", "hasBroadcastChannel", "hasCourseInstance", "hasDeliveryMethod", "hasDigitalDocumentPermission", "hasMap", "hasMenu", "hasMenuItem", "hasMenuSection", "hasOccupation",
    "hasOfferCatalog", "hasPOS", "hasPart", "headline", "height", "highPrice", "hiringOrganization", "homeLocation", "homeTeam", "honorificPrefix",
    "honorificSuffix", "hostingOrganization", "hoursAvailable", "httpMethod", "iataCode", "icaoCode", "identifier", "illustrator", "image", "inAlbum",
    "inBroadcastLineup", "inLanguage", "inPlaylist", "incentiveCompensation", "incentives", "includedComposition", "includedDataCatalog", "includedInDataCatalog", "includesObject", "industry",
    "ineligibleRegion", "ingredients", "installUrl", "instructor", "instrument", "interactionCount", "interactionService", "interactionStatistic", "interactionType", "interactivityType",
    "interestRate", "inventoryLevel", "isAccessibleForFree", "isAccessoryOrSparePartFor", "isBasedOn", "isBasedOnUrl", "isConsumableFor", "isFamilyFriendly", "isGift", "isLiveBroadcast",
    "isPartOf", "isRelatedTo", "isSimilarTo", "isVariantOf", "isbn", "isicV4", "isrcCode", "issn", "issueNumber", "issuedBy",
    "issuedThrough", "iswcCode", "item", "itemCondition", "itemListElement", "itemListOrder", "itemOffered", "itemReviewed", "itemShipped", "jobBenefits",
    "jobLocation", "jobTitle", "keywords", "knownVehicleDamages", "knows", "landlord", "language", "lastReviewed", "latitude", "learningResourceType",
    "legalName", "leiCode", "lender", "lesser", "lesserOrEqual", "license", "line", "liveBlogUpdate", "loanTerm", "location",
    "locationCreated", "lodgingUnitDescription", "lodgingUnitType", "logo", "longitude", "loser", "lowPrice", "lyricist", "lyrics", "mainContentOfPage",
    "mainEntity", "mainEntityOfPage", "makesOffer", "manufacturer", "map", "mapType", "maps", "material", "maxPrice", "maxValue",
    "maximumAttendeeCapacity", "mealService", "median", "member", "memberOf", "members", "membershipNumber", "memoryRequirements", "mentions", "menu",
    "menuAddOn", "merchant", "messageAttachment", "mileageFromOdometer", "minPrice", "minValue", "minimumPaymentDue", "model", "modifiedTime", "mpn",
    "multipleValues", "musicArrangement", "musicBy", "musicCompositionForm", "musicGroupMember", "musicReleaseFormat", "musicalKey", "naics", "name", "namedPosition",
    "nationality", "netWorth", "nextItem", "nonEqual", "numAdults", "numChildren", "numTracks", "numberOfAirbags", "numberOfAxles", "numberOfBeds",
    "numberOfDoors", "numberOfEmployees", "numberOfEpisodes", "numberOfForwardGears", "numberOfItems", "numberOfPages", "numberOfPlayers", "numberOfPreviousOwners", "numberOfRooms", "numberOfSeasons",
    "numberedPosition", "nutrition", "object", "occupancy", "occupationLocation", "occupationalCategory", "offerCount", "offeredBy", "offers", "openingHours",
    "openingHoursSpecification", "opens", "operatingSystem", "opponent", "option", "orderDate", "orderDelivery", "orderItemNumber", "orderItemStatus", "orderNumber",
    "orderQuantity", "orderStatus", "orderedItem", "organizer", "originAddress", "ownedFrom", "ownedThrough", "owns", "pageEnd", "pageStart",
    "pagination", "parent", "parentItem", "parentOrganization", "parentService", "parents", "partOfEpisode", "partOfInvoice", "partOfOrder", "partOfSeason",
    "partOfSeries", "partOfTVSeries", "participant", "partySize", "passengerPriorityStatus", "passengerSequenceNumber", "paymentAccepted", "paymentDue", "paymentDueDate", "paymentMethod",
    "paymentMethodId", "paymentStatus", "paymentUrl", "percentile10", "percentile25", "percentile75", "percentile90", "performTime", "performer", "performerIn",
    "performers", "permissionType", "permissions", "permitAudience", "permittedUsage", "petsAllowed", "photo", "photos", "pickupLocation", "pickupTime",
    "playMode", "playerType", "playersOnline", "polygon", "position", "postOfficeBoxNumber", "postalCode", "potentialAction", "predecessorOf", "prepTime",
    "previousItem", "previousStartDate", "price", "priceComponent", "priceCurrency", "priceRange", "priceSpecification", "priceType", "priceValidUntil", "primaryImageOfPage",
    "printColumn", "printEdition", "printPage", "printSection", "processingTime", "processorRequirements", "producer", "produces", "productID", "productSupported",
    "productionCompany", "productionDate", "proficiencyLevel", "programMembershipUsed", "programName", "programmingLanguage", "programmingModel", "propertyID", "proteinContent", "provider",
    "providerMobility", "providesBroadcastService", "providesService", "publicAccess", "publication", "publishedOn", "publisher", "publishingPrinciples", "purchaseDate", "query",
    "quest", "question", "ratingCount", "ratingValue", "readonlyValue", "realEstateAgent", "recipe", "recipeCategory", "recipeCuisine", "recipeIngredient",
    "recipeInstructions", "recipeYield", "recipient", "recordLabel", "recordedAs", "recordedAt", "recordedIn", "recordingOf", "referenceQuantity", "referencesOrder",
    "regionsAllowed", "relatedLink", "relatedTo", "releaseDate", "releaseNotes", "releaseOf", "releasedEvent", "relevantOccupation", "remainingAttendeeCapacity", "replacee",
    "replacer", "replyToUrl", "reportNumber", "representativeOfPage", "requiredCollateral", "requiredGender", "requiredMaxAge", "requiredMinAge", "requiredQuantity", "requirements",
    "requiresSubscription", "reservationFor", "reservationId", "reservationStatus", "reservedTicket", "responsibilities", "result", "resultComment", "resultReview", "review",
    "reviewAspect", "reviewBody", "reviewCount", "reviewRating", "reviewedBy", "reviews", "roleName", "rsvpResponse", "runtime", "runtimePlatform",
    "salaryCurrency", "sameAs", "sampleType", "saturatedFatContent", "scheduledPaymentDate", "scheduledTime", "schemaVersion", "screenCount", "screenshot", "season",
    "seasonNumber", "seasons", "seatNumber", "seatRow", "seatSection", "seatingType", "securityScreening", "seeks", "seller", "sender",
    "serialNumber", "serverStatus", "servesCuisine", "serviceArea", "serviceAudience", "serviceLocation", "serviceOperator", "serviceOutput", "servicePhone", "servicePostalAddress",
    "serviceSmsNumber", "serviceType", "serviceUrl", "servingSize", "sharedContent", "sibling", "siblings", "significantLink", "significantLinks", "skills",
    "sku", "slogan", "smokingAllowed", "sodiumContent", "softwareAddOn", "softwareHelp", "softwareRequirements", "softwareVersion", "sourceOrganization", "spatial",
    "spatialCoverage", "speakable", "specialCommitments", "specialOpeningHoursSpecification", "specialty", "sponsor", "sport", "sportsActivityLocation", "sportsEvent", "sportsTeam",
    "spouse", "starRating", "startDate", "startTime", "steeringPosition", "step", "stepValue", "steps", "storageRequirements", "streetAddress",
    "subEvent", "subEvents", "subOrganization", "subReservation", "subjectOf", "subtitleLanguage", "successorOf", "sugarContent", "suggestedAnswer", "suggestedGender",
    "suggestedMaxAge", "suggestedMinAge", "suitableForDiet", "superEvent", "supply", "supportingData", "surface", "target", "targetCollection", "targetDescription",
    "targetName", "targetPlatform", "targetProduct", "targetUrl", "taxID", "telephone", "temporal", "temporalCoverage", "text", "thumbnail",
    "thumbnailUrl", "tickerSymbol", "ticketNumber", "ticketToken", "ticketedSeat", "timeRequired", "title", "toLocation", "toRecipient", "tool",
    "totalPaymentDue", "totalPrice", "totalTime", "touristType", "track", "trackingNumber", "trackingUrl", "tracks", "trailer", "trainName",
    "trainNumber", "transFatContent", "transcript", "translator", "typeOfBed", "typeOfGood", "typicalAgeRange", "underName", "unitCode", "unitText",
    "unsaturatedFatContent", "uploadDate", "upvoteCount", "url", "urlTemplate", "userInteractionCount", "validFor", "validFrom", "validIn", "validThrough",
    "validUntil", "value", "valueAddedTaxIncluded", "valueMaxLength", "valueMinLength", "valueName", "valuePattern", "valueReference", "valueRequired", "vatID",
    "vehicleConfiguration", "vehicleEngine", "vehicleIdentificationNumber", "vehicleInteriorColor", "vehicleInteriorType", "vehicleModelDate", "vehicleSeatingCapacity", "vehicleTransmission", "vendor", "version",
    "video", "videoFormat", "videoFrameSize", "videoQuality", "volumeNumber", "warranty", "warrantyPromise", "warrantyScope", "webCheckinTime", "weight",
    "width", "winner", "wordCount", "workExample", "workFeatured", "workHours", "workLocation", "workPerformed", "workPresented", "worksFor",
    "worstRating", "xpath", "yearlyRevenue", "yearsInOperation", "yield"
) {
    val about by iriStore
    val acceptedAnswer by iriStore
    val acceptedOffer by iriStore
    val acceptedPaymentMethod by iriStore
    val acceptsReservations by iriStore
    val accessCode by iriStore
    val accessMode by iriStore
    val accessModeSufficient by iriStore
    val accessibilityAPI by iriStore
    val accessibilityControl by iriStore
    val accessibilityFeature by iriStore
    val accessibilityHazard by iriStore
    val accessibilitySummary by iriStore
    val accountId by iriStore
    val accountablePerson by iriStore
    val acquiredFrom by iriStore
    val actionAccessibilityRequirement by iriStore
    val actionApplication by iriStore
    val actionOption by iriStore
    val actionPlatform by iriStore
    val actionStatus by iriStore
    val actor by iriStore
    val actors by iriStore
    val addOn by iriStore
    val additionalName by iriStore
    val additionalNumberOfGuests by iriStore
    val additionalProperty by iriStore
    val additionalType by iriStore
    val address by iriStore
    val addressCountry by iriStore
    val addressLocality by iriStore
    val addressRegion by iriStore
    val advanceBookingRequirement by iriStore
    val affiliation by iriStore
    val afterMedia by iriStore
    val agent by iriStore
    val aggregateRating by iriStore
    val aircraft by iriStore
    val album by iriStore
    val albumProductionType by iriStore
    val albumRelease by iriStore
    val albumReleaseType by iriStore
    val albums by iriStore
    val alignmentType by iriStore
    val alternateName by iriStore
    val alternativeHeadline by iriStore
    val alumni by iriStore
    val alumniOf by iriStore
    val amenityFeature by iriStore
    val amount by iriStore
    val amountOfThisGood by iriStore
    val annualPercentageRate by iriStore
    val answerCount by iriStore
    val application by iriStore
    val applicationCategory by iriStore
    val applicationSubCategory by iriStore
    val applicationSuite by iriStore
    val appliesToDeliveryMethod by iriStore
    val appliesToPaymentMethod by iriStore
    val area by iriStore
    val areaServed by iriStore
    val arrivalAirport by iriStore
    val arrivalBusStop by iriStore
    val arrivalGate by iriStore
    val arrivalPlatform by iriStore
    val arrivalStation by iriStore
    val arrivalTerminal by iriStore
    val arrivalTime by iriStore
    val artEdition by iriStore
    val artMedium by iriStore
    val artform by iriStore
    val articleBody by iriStore
    val articleSection by iriStore
    val artworkSurface by iriStore
    val assembly by iriStore
    val assemblyVersion by iriStore
    val associatedArticle by iriStore
    val associatedMedia by iriStore
    val athlete by iriStore
    val attendee by iriStore
    val attendees by iriStore
    val audience by iriStore
    val audienceType by iriStore
    val audio by iriStore
    val authenticator by iriStore
    val author by iriStore
    val availability by iriStore
    val availabilityEnds by iriStore
    val availabilityStarts by iriStore
    val availableAtOrFrom by iriStore
    val availableChannel by iriStore
    val availableDeliveryMethod by iriStore
    val availableFrom by iriStore
    val availableLanguage by iriStore
    val availableOnDevice by iriStore
    val availableThrough by iriStore
    val award by iriStore
    val awards by iriStore
    val awayTeam by iriStore
    val baseSalary by iriStore
    val bccRecipient by iriStore
    val bed by iriStore
    val beforeMedia by iriStore
    val benefits by iriStore
    val bestRating by iriStore
    val billingAddress by iriStore
    val billingIncrement by iriStore
    val billingPeriod by iriStore
    val birthDate by iriStore
    val birthPlace by iriStore
    val bitrate by iriStore
    val blogPost by iriStore
    val blogPosts by iriStore
    val boardingGroup by iriStore
    val boardingPolicy by iriStore
    val bookEdition by iriStore
    val bookFormat by iriStore
    val bookingAgent by iriStore
    val bookingTime by iriStore
    val borrower by iriStore
    val box by iriStore
    val branchCode by iriStore
    val branchOf by iriStore
    val brand by iriStore
    val breadcrumb by iriStore
    val broadcastAffiliateOf by iriStore
    val broadcastChannelId by iriStore
    val broadcastDisplayName by iriStore
    val broadcastFrequency by iriStore
    val broadcastFrequencyValue by iriStore
    val broadcastOfEvent by iriStore
    val broadcastServiceTier by iriStore
    val broadcastTimezone by iriStore
    val broadcaster by iriStore
    val broker by iriStore
    val browserRequirements by iriStore
    val busName by iriStore
    val busNumber by iriStore
    val businessFunction by iriStore
    val buyer by iriStore
    val byArtist by iriStore
    val calories by iriStore
    val candidate by iriStore
    val caption by iriStore
    val carbohydrateContent by iriStore
    val cargoVolume by iriStore
    val carrier by iriStore
    val carrierRequirements by iriStore
    val catalog by iriStore
    val catalogNumber by iriStore
    val category by iriStore
    val ccRecipient by iriStore
    val character by iriStore
    val characterAttribute by iriStore
    val characterName by iriStore
    val cheatCode by iriStore
    val checkinTime by iriStore
    val checkoutTime by iriStore
    val childMaxAge by iriStore
    val childMinAge by iriStore
    val children by iriStore
    val cholesterolContent by iriStore
    val circle by iriStore
    val citation by iriStore
    val claimReviewed by iriStore
    val clipNumber by iriStore
    val closes by iriStore
    val coach by iriStore
    val codeRepository by iriStore
    val codeSampleType by iriStore
    val colleague by iriStore
    val colleagues by iriStore
    val collection by iriStore
    val color by iriStore
    val comment by iriStore
    val commentCount by iriStore
    val commentText by iriStore
    val commentTime by iriStore
    val competitor by iriStore
    val composer by iriStore
    val confirmationNumber by iriStore
    val contactOption by iriStore
    val contactPoint by iriStore
    val contactPoints by iriStore
    val contactType by iriStore
    val containedIn by iriStore
    val containedInPlace by iriStore
    val containsPlace by iriStore
    val containsSeason by iriStore
    val contentLocation by iriStore
    val contentRating by iriStore
    val contentSize by iriStore
    val contentType by iriStore
    val contentUrl by iriStore
    val contributor by iriStore
    val cookTime by iriStore
    val cookingMethod by iriStore
    val copyrightHolder by iriStore
    val copyrightYear by iriStore
    val countriesNotSupported by iriStore
    val countriesSupported by iriStore
    val countryOfOrigin by iriStore
    val course by iriStore
    val courseCode by iriStore
    val courseMode by iriStore
    val coursePrerequisites by iriStore
    val coverageEndTime by iriStore
    val coverageStartTime by iriStore
    val creator by iriStore
    val creditedTo by iriStore
    val cssSelector by iriStore
    val currenciesAccepted by iriStore
    val currency by iriStore
    val customer by iriStore
    val dataFeedElement by iriStore
    val dataset by iriStore
    val datasetTimeInterval by iriStore
    val dateCreated by iriStore
    val dateDeleted by iriStore
    val dateIssued by iriStore
    val dateModified by iriStore
    val datePosted by iriStore
    val datePublished by iriStore
    val dateRead by iriStore
    val dateReceived by iriStore
    val dateSent by iriStore
    val dateVehicleFirstRegistered by iriStore
    val dateline by iriStore
    val dayOfWeek by iriStore
    val deathDate by iriStore
    val deathPlace by iriStore
    val defaultValue by iriStore
    val deliveryAddress by iriStore
    val deliveryLeadTime by iriStore
    val deliveryMethod by iriStore
    val deliveryStatus by iriStore
    val department by iriStore
    val departureAirport by iriStore
    val departureBusStop by iriStore
    val departureGate by iriStore
    val departurePlatform by iriStore
    val departureStation by iriStore
    val departureTerminal by iriStore
    val departureTime by iriStore
    val dependencies by iriStore
    val depth by iriStore
    val description by iriStore
    val device by iriStore
    val director by iriStore
    val directors by iriStore
    val disambiguatingDescription by iriStore
    val discount by iriStore
    val discountCode by iriStore
    val discountCurrency by iriStore
    val discusses by iriStore
    val discussionUrl by iriStore
    val dissolutionDate by iriStore
    val distance by iriStore
    val distribution by iriStore
    val doorTime by iriStore
    val downloadUrl by iriStore
    val downvoteCount by iriStore
    val driveWheelConfiguration by iriStore
    val dropoffLocation by iriStore
    val dropoffTime by iriStore
    val duns by iriStore
    val duration by iriStore
    val durationOfWarranty by iriStore
    val duringMedia by iriStore
    val editor by iriStore
    val educationalAlignment by iriStore
    val educationalFramework by iriStore
    val educationalRole by iriStore
    val educationalUse by iriStore
    val elevation by iriStore
    val eligibleCustomerType by iriStore
    val eligibleDuration by iriStore
    val eligibleQuantity by iriStore
    val eligibleRegion by iriStore
    val eligibleTransactionVolume by iriStore
    val email by iriStore
    val embedUrl by iriStore
    val employee by iriStore
    val employees by iriStore
    val employmentType by iriStore
    val encodesCreativeWork by iriStore
    val encoding by iriStore
    val encodingFormat by iriStore
    val encodingType by iriStore
    val encodings by iriStore
    val endDate by iriStore
    val endTime by iriStore
    val endorsee by iriStore
    val entertainmentBusiness by iriStore
    val episode by iriStore
    val episodeNumber by iriStore
    val episodes by iriStore
    val equal by iriStore
    val error by iriStore
    val estimatedCost by iriStore
    val estimatedFlightDuration by iriStore
    val estimatedSalary by iriStore
    val event by iriStore
    val eventStatus by iriStore
    val events by iriStore
    val exampleOfWork by iriStore
    val executableLibraryName by iriStore
    val exerciseCourse by iriStore
    val exifData by iriStore
    val expectedArrivalFrom by iriStore
    val expectedArrivalUntil by iriStore
    val expectsAcceptanceOf by iriStore
    val experienceRequirements by iriStore
    val expires by iriStore
    val familyName by iriStore
    val fatContent by iriStore
    val faxNumber by iriStore
    val featureList by iriStore
    val feesAndCommissionsSpecification by iriStore
    val fiberContent by iriStore
    val fileFormat by iriStore
    val fileSize by iriStore
    val firstPerformance by iriStore
    val flightDistance by iriStore
    val flightNumber by iriStore
    val floorSize by iriStore
    val followee by iriStore
    val follows by iriStore
    val foodEstablishment by iriStore
    val foodEvent by iriStore
    val founder by iriStore
    val founders by iriStore
    val foundingDate by iriStore
    val foundingLocation by iriStore
    val free by iriStore
    val fromLocation by iriStore
    val fuelConsumption by iriStore
    val fuelEfficiency by iriStore
    val fuelType by iriStore
    val funder by iriStore
    val game by iriStore
    val gameItem by iriStore
    val gameLocation by iriStore
    val gamePlatform by iriStore
    val gameServer by iriStore
    val gameTip by iriStore
    val gender by iriStore
    val genre by iriStore
    val geo by iriStore
    val geoContains by iriStore
    val geoCoveredBy by iriStore
    val geoCovers by iriStore
    val geoCrosses by iriStore
    val geoDisjoint by iriStore
    val geoEquals by iriStore
    val geoIntersects by iriStore
    val geoMidpoint by iriStore
    val geoOverlaps by iriStore
    val geoRadius by iriStore
    val geoTouches by iriStore
    val geoWithin by iriStore
    val geographicArea by iriStore
    val givenName by iriStore
    val globalLocationNumber by iriStore
    val grantee by iriStore
    val greater by iriStore
    val greaterOrEqual by iriStore
    val gtin12 by iriStore
    val gtin13 by iriStore
    val gtin14 by iriStore
    val gtin8 by iriStore
    val hasBroadcastChannel by iriStore
    val hasCourseInstance by iriStore
    val hasDeliveryMethod by iriStore
    val hasDigitalDocumentPermission by iriStore
    val hasMap by iriStore
    val hasMenu by iriStore
    val hasMenuItem by iriStore
    val hasMenuSection by iriStore
    val hasOccupation by iriStore
    val hasOfferCatalog by iriStore
    val hasPOS by iriStore
    val hasPart by iriStore
    val headline by iriStore
    val height by iriStore
    val highPrice by iriStore
    val hiringOrganization by iriStore
    val homeLocation by iriStore
    val homeTeam by iriStore
    val honorificPrefix by iriStore
    val honorificSuffix by iriStore
    val hostingOrganization by iriStore
    val hoursAvailable by iriStore
    val httpMethod by iriStore
    val iataCode by iriStore
    val icaoCode by iriStore
    val identifier by iriStore
    val illustrator by iriStore
    val image by iriStore
    val inAlbum by iriStore
    val inBroadcastLineup by iriStore
    val inLanguage by iriStore
    val inPlaylist by iriStore
    val incentiveCompensation by iriStore
    val incentives by iriStore
    val includedComposition by iriStore
    val includedDataCatalog by iriStore
    val includedInDataCatalog by iriStore
    val includesObject by iriStore
    val industry by iriStore
    val ineligibleRegion by iriStore
    val ingredients by iriStore
    val installUrl by iriStore
    val instructor by iriStore
    val instrument by iriStore
    val interactionCount by iriStore
    val interactionService by iriStore
    val interactionStatistic by iriStore
    val interactionType by iriStore
    val interactivityType by iriStore
    val interestRate by iriStore
    val inventoryLevel by iriStore
    val isAccessibleForFree by iriStore
    val isAccessoryOrSparePartFor by iriStore
    val isBasedOn by iriStore
    val isBasedOnUrl by iriStore
    val isConsumableFor by iriStore
    val isFamilyFriendly by iriStore
    val isGift by iriStore
    val isLiveBroadcast by iriStore
    val isPartOf by iriStore
    val isRelatedTo by iriStore
    val isSimilarTo by iriStore
    val isVariantOf by iriStore
    val isbn by iriStore
    val isicV4 by iriStore
    val isrcCode by iriStore
    val issn by iriStore
    val issueNumber by iriStore
    val issuedBy by iriStore
    val issuedThrough by iriStore
    val iswcCode by iriStore
    val item by iriStore
    val itemCondition by iriStore
    val itemListElement by iriStore
    val itemListOrder by iriStore
    val itemOffered by iriStore
    val itemReviewed by iriStore
    val itemShipped by iriStore
    val jobBenefits by iriStore
    val jobLocation by iriStore
    val jobTitle by iriStore
    val keywords by iriStore
    val knownVehicleDamages by iriStore
    val knows by iriStore
    val landlord by iriStore
    val language by iriStore
    val lastReviewed by iriStore
    val latitude by iriStore
    val learningResourceType by iriStore
    val legalName by iriStore
    val leiCode by iriStore
    val lender by iriStore
    val lesser by iriStore
    val lesserOrEqual by iriStore
    val license by iriStore
    val line by iriStore
    val liveBlogUpdate by iriStore
    val loanTerm by iriStore
    val location by iriStore
    val locationCreated by iriStore
    val lodgingUnitDescription by iriStore
    val lodgingUnitType by iriStore
    val logo by iriStore
    val longitude by iriStore
    val loser by iriStore
    val lowPrice by iriStore
    val lyricist by iriStore
    val lyrics by iriStore
    val mainContentOfPage by iriStore
    val mainEntity by iriStore
    val mainEntityOfPage by iriStore
    val makesOffer by iriStore
    val manufacturer by iriStore
    val map by iriStore
    val mapType by iriStore
    val maps by iriStore
    val material by iriStore
    val maxPrice by iriStore
    val maxValue by iriStore
    val maximumAttendeeCapacity by iriStore
    val mealService by iriStore
    val median by iriStore
    val member by iriStore
    val memberOf by iriStore
    val members by iriStore
    val membershipNumber by iriStore
    val memoryRequirements by iriStore
    val mentions by iriStore
    val menu by iriStore
    val menuAddOn by iriStore
    val merchant by iriStore
    val messageAttachment by iriStore
    val mileageFromOdometer by iriStore
    val minPrice by iriStore
    val minValue by iriStore
    val minimumPaymentDue by iriStore
    val model by iriStore
    val modifiedTime by iriStore
    val mpn by iriStore
    val multipleValues by iriStore
    val musicArrangement by iriStore
    val musicBy by iriStore
    val musicCompositionForm by iriStore
    val musicGroupMember by iriStore
    val musicReleaseFormat by iriStore
    val musicalKey by iriStore
    val naics by iriStore
    val name by iriStore
    val namedPosition by iriStore
    val nationality by iriStore
    val netWorth by iriStore
    val nextItem by iriStore
    val nonEqual by iriStore
    val numAdults by iriStore
    val numChildren by iriStore
    val numTracks by iriStore
    val numberOfAirbags by iriStore
    val numberOfAxles by iriStore
    val numberOfBeds by iriStore
    val numberOfDoors by iriStore
    val numberOfEmployees by iriStore
    val numberOfEpisodes by iriStore
    val numberOfForwardGears by iriStore
    val numberOfItems by iriStore
    val numberOfPages by iriStore
    val numberOfPlayers by iriStore
    val numberOfPreviousOwners by iriStore
    val numberOfRooms by iriStore
    val numberOfSeasons by iriStore
    val numberedPosition by iriStore
    val nutrition by iriStore
    val `object` by iriStore
    val occupancy by iriStore
    val occupationLocation by iriStore
    val occupationalCategory by iriStore
    val offerCount by iriStore
    val offeredBy by iriStore
    val offers by iriStore
    val openingHours by iriStore
    val openingHoursSpecification by iriStore
    val opens by iriStore
    val operatingSystem by iriStore
    val opponent by iriStore
    val option by iriStore
    val orderDate by iriStore
    val orderDelivery by iriStore
    val orderItemNumber by iriStore
    val orderItemStatus by iriStore
    val orderNumber by iriStore
    val orderQuantity by iriStore
    val orderStatus by iriStore
    val orderedItem by iriStore
    val organizer by iriStore
    val originAddress by iriStore
    val ownedFrom by iriStore
    val ownedThrough by iriStore
    val owns by iriStore
    val pageEnd by iriStore
    val pageStart by iriStore
    val pagination by iriStore
    val parent by iriStore
    val parentItem by iriStore
    val parentOrganization by iriStore
    val parentService by iriStore
    val parents by iriStore
    val partOfEpisode by iriStore
    val partOfInvoice by iriStore
    val partOfOrder by iriStore
    val partOfSeason by iriStore
    val partOfSeries by iriStore
    val partOfTVSeries by iriStore
    val participant by iriStore
    val partySize by iriStore
    val passengerPriorityStatus by iriStore
    val passengerSequenceNumber by iriStore
    val paymentAccepted by iriStore
    val paymentDue by iriStore
    val paymentDueDate by iriStore
    val paymentMethod by iriStore
    val paymentMethodId by iriStore
    val paymentStatus by iriStore
    val paymentUrl by iriStore
    val percentile10 by iriStore
    val percentile25 by iriStore
    val percentile75 by iriStore
    val percentile90 by iriStore
    val performTime by iriStore
    val performer by iriStore
    val performerIn by iriStore
    val performers by iriStore
    val permissionType by iriStore
    val permissions by iriStore
    val permitAudience by iriStore
    val permittedUsage by iriStore
    val petsAllowed by iriStore
    val photo by iriStore
    val photos by iriStore
    val pickupLocation by iriStore
    val pickupTime by iriStore
    val playMode by iriStore
    val playerType by iriStore
    val playersOnline by iriStore
    val polygon by iriStore
    val position by iriStore
    val postOfficeBoxNumber by iriStore
    val postalCode by iriStore
    val potentialAction by iriStore
    val predecessorOf by iriStore
    val prepTime by iriStore
    val previousItem by iriStore
    val previousStartDate by iriStore
    val price by iriStore
    val priceComponent by iriStore
    val priceCurrency by iriStore
    val priceRange by iriStore
    val priceSpecification by iriStore
    val priceType by iriStore
    val priceValidUntil by iriStore
    val primaryImageOfPage by iriStore
    val printColumn by iriStore
    val printEdition by iriStore
    val printPage by iriStore
    val printSection by iriStore
    val processingTime by iriStore
    val processorRequirements by iriStore
    val producer by iriStore
    val produces by iriStore
    val productID by iriStore
    val productSupported by iriStore
    val productionCompany by iriStore
    val productionDate by iriStore
    val proficiencyLevel by iriStore
    val programMembershipUsed by iriStore
    val programName by iriStore
    val programmingLanguage by iriStore
    val programmingModel by iriStore
    val propertyID by iriStore
    val proteinContent by iriStore
    val provider by iriStore
    val providerMobility by iriStore
    val providesBroadcastService by iriStore
    val providesService by iriStore
    val publicAccess by iriStore
    val publication by iriStore
    val publishedOn by iriStore
    val publisher by iriStore
    val publishingPrinciples by iriStore
    val purchaseDate by iriStore
    val query by iriStore
    val quest by iriStore
    val question by iriStore
    val ratingCount by iriStore
    val ratingValue by iriStore
    val readonlyValue by iriStore
    val realEstateAgent by iriStore
    val recipe by iriStore
    val recipeCategory by iriStore
    val recipeCuisine by iriStore
    val recipeIngredient by iriStore
    val recipeInstructions by iriStore
    val recipeYield by iriStore
    val recipient by iriStore
    val recordLabel by iriStore
    val recordedAs by iriStore
    val recordedAt by iriStore
    val recordedIn by iriStore
    val recordingOf by iriStore
    val referenceQuantity by iriStore
    val referencesOrder by iriStore
    val regionsAllowed by iriStore
    val relatedLink by iriStore
    val relatedTo by iriStore
    val releaseDate by iriStore
    val releaseNotes by iriStore
    val releaseOf by iriStore
    val releasedEvent by iriStore
    val relevantOccupation by iriStore
    val remainingAttendeeCapacity by iriStore
    val replacee by iriStore
    val replacer by iriStore
    val replyToUrl by iriStore
    val reportNumber by iriStore
    val representativeOfPage by iriStore
    val requiredCollateral by iriStore
    val requiredGender by iriStore
    val requiredMaxAge by iriStore
    val requiredMinAge by iriStore
    val requiredQuantity by iriStore
    val requirements by iriStore
    val requiresSubscription by iriStore
    val reservationFor by iriStore
    val reservationId by iriStore
    val reservationStatus by iriStore
    val reservedTicket by iriStore
    val responsibilities by iriStore
    val result by iriStore
    val resultComment by iriStore
    val resultReview by iriStore
    val review by iriStore
    val reviewAspect by iriStore
    val reviewBody by iriStore
    val reviewCount by iriStore
    val reviewRating by iriStore
    val reviewedBy by iriStore
    val reviews by iriStore
    val roleName by iriStore
    val rsvpResponse by iriStore
    val runtime by iriStore
    val runtimePlatform by iriStore
    val salaryCurrency by iriStore
    val sameAs by iriStore
    val sampleType by iriStore
    val saturatedFatContent by iriStore
    val scheduledPaymentDate by iriStore
    val scheduledTime by iriStore
    val schemaVersion by iriStore
    val screenCount by iriStore
    val screenshot by iriStore
    val season by iriStore
    val seasonNumber by iriStore
    val seasons by iriStore
    val seatNumber by iriStore
    val seatRow by iriStore
    val seatSection by iriStore
    val seatingType by iriStore
    val securityScreening by iriStore
    val seeks by iriStore
    val seller by iriStore
    val sender by iriStore
    val serialNumber by iriStore
    val serverStatus by iriStore
    val servesCuisine by iriStore
    val serviceArea by iriStore
    val serviceAudience by iriStore
    val serviceLocation by iriStore
    val serviceOperator by iriStore
    val serviceOutput by iriStore
    val servicePhone by iriStore
    val servicePostalAddress by iriStore
    val serviceSmsNumber by iriStore
    val serviceType by iriStore
    val serviceUrl by iriStore
    val servingSize by iriStore
    val sharedContent by iriStore
    val sibling by iriStore
    val siblings by iriStore
    val significantLink by iriStore
    val significantLinks by iriStore
    val skills by iriStore
    val sku by iriStore
    val slogan by iriStore
    val smokingAllowed by iriStore
    val sodiumContent by iriStore
    val softwareAddOn by iriStore
    val softwareHelp by iriStore
    val softwareRequirements by iriStore
    val softwareVersion by iriStore
    val sourceOrganization by iriStore
    val spatial by iriStore
    val spatialCoverage by iriStore
    val speakable by iriStore
    val specialCommitments by iriStore
    val specialOpeningHoursSpecification by iriStore
    val specialty by iriStore
    val sponsor by iriStore
    val sport by iriStore
    val sportsActivityLocation by iriStore
    val sportsEvent by iriStore
    val sportsTeam by iriStore
    val spouse by iriStore
    val starRating by iriStore
    val startDate by iriStore
    val startTime by iriStore
    val steeringPosition by iriStore
    val step by iriStore
    val stepValue by iriStore
    val steps by iriStore
    val storageRequirements by iriStore
    val streetAddress by iriStore
    val subEvent by iriStore
    val subEvents by iriStore
    val subOrganization by iriStore
    val subReservation by iriStore
    val subjectOf by iriStore
    val subtitleLanguage by iriStore
    val successorOf by iriStore
    val sugarContent by iriStore
    val suggestedAnswer by iriStore
    val suggestedGender by iriStore
    val suggestedMaxAge by iriStore
    val suggestedMinAge by iriStore
    val suitableForDiet by iriStore
    val superEvent by iriStore
    val supply by iriStore
    val supportingData by iriStore
    val surface by iriStore
    val target by iriStore
    val targetCollection by iriStore
    val targetDescription by iriStore
    val targetName by iriStore
    val targetPlatform by iriStore
    val targetProduct by iriStore
    val targetUrl by iriStore
    val taxID by iriStore
    val telephone by iriStore
    val temporal by iriStore
    val temporalCoverage by iriStore
    val text by iriStore
    val thumbnail by iriStore
    val thumbnailUrl by iriStore
    val tickerSymbol by iriStore
    val ticketNumber by iriStore
    val ticketToken by iriStore
    val ticketedSeat by iriStore
    val timeRequired by iriStore
    val title by iriStore
    val toLocation by iriStore
    val toRecipient by iriStore
    val tool by iriStore
    val totalPaymentDue by iriStore
    val totalPrice by iriStore
    val totalTime by iriStore
    val touristType by iriStore
    val track by iriStore
    val trackingNumber by iriStore
    val trackingUrl by iriStore
    val tracks by iriStore
    val trailer by iriStore
    val trainName by iriStore
    val trainNumber by iriStore
    val transFatContent by iriStore
    val transcript by iriStore
    val translator by iriStore
    val typeOfBed by iriStore
    val typeOfGood by iriStore
    val typicalAgeRange by iriStore
    val underName by iriStore
    val unitCode by iriStore
    val unitText by iriStore
    val unsaturatedFatContent by iriStore
    val uploadDate by iriStore
    val upvoteCount by iriStore
    val url by iriStore
    val urlTemplate by iriStore
    val userInteractionCount by iriStore
    val validFor by iriStore
    val validFrom by iriStore
    val validIn by iriStore
    val validThrough by iriStore
    val validUntil by iriStore
    val value by iriStore
    val valueAddedTaxIncluded by iriStore
    val valueMaxLength by iriStore
    val valueMinLength by iriStore
    val valueName by iriStore
    val valuePattern by iriStore
    val valueReference by iriStore
    val valueRequired by iriStore
    val vatID by iriStore
    val vehicleConfiguration by iriStore
    val vehicleEngine by iriStore
    val vehicleIdentificationNumber by iriStore
    val vehicleInteriorColor by iriStore
    val vehicleInteriorType by iriStore
    val vehicleModelDate by iriStore
    val vehicleSeatingCapacity by iriStore
    val vehicleTransmission by iriStore
    val vendor by iriStore
    val version by iriStore
    val video by iriStore
    val videoFormat by iriStore
    val videoFrameSize by iriStore
    val videoQuality by iriStore
    val volumeNumber by iriStore
    val warranty by iriStore
    val warrantyPromise by iriStore
    val warrantyScope by iriStore
    val webCheckinTime by iriStore
    val weight by iriStore
    val width by iriStore
    val winner by iriStore
    val wordCount by iriStore
    val workExample by iriStore
    val workFeatured by iriStore
    val workHours by iriStore
    val workLocation by iriStore
    val workPerformed by iriStore
    val workPresented by iriStore
    val worksFor by iriStore
    val worstRating by iriStore
    val xpath by iriStore
    val yearlyRevenue by iriStore
    val yearsInOperation by iriStore
    val yield by iriStore
}
