package net.subroh0508.otonashi.vocabularies.foaf
import net.subroh0508.otonashi.triples.TripleFacade
import net.subroh0508.otonashi.triples.extensions.get
import net.subroh0508.otonashi.triples.vocabulary.IriVocabulary

/*
 * This file was auto generated by otonashi-vocabularies-generator plugin
 *
 */

val Set<IriVocabulary>.foafC get() = get(FoafClass::class)
val TripleFacade.foafC get() = iri.foafC

val Set<IriVocabulary>.foafP get() = get(FoafProperty::class)
val TripleFacade.foafP get() = iri.foafP
