package net.subroh0508.otonashi.vocabularies.foaf

import net.subroh0508.otonashi.triples.vocabulary.IriVocabulary

/*
 * This file was auto generated by otonashi-vocabularies-generator plugin
 *
 */

object FoafProperty : IriVocabulary(
    "foaf",
    "account", "accountName", "accountServiceHomepage", "age", "aimChatID", "based_near", "birthday", "currentProject", "depiction", "depicts",
    "dnaChecksum", "familyName", "family_name", "firstName", "focus", "fundedBy", "geekcode", "gender", "givenName", "givenname",
    "holdsAccount", "homepage", "icqChatID", "img", "interest", "isPrimaryTopicOf", "jabberID", "knows", "lastName", "logo",
    "made", "maker", "mbox", "mbox_sha1sum", "member", "membershipClass", "msnChatID", "myersBriggs", "name", "nick",
    "openid", "page", "pastProject", "phone", "plan", "primaryTopic", "publications", "schoolHomepage", "sha1", "skypeID",
    "status", "surname", "theme", "thumbnail", "tipjar", "title", "topic", "topic_interest", "weblog", "workInfoHomepage",
    "workplaceHomepage", "yahooChatID"
) {
    val account by iriStore
    val accountName by iriStore
    val accountServiceHomepage by iriStore
    val age by iriStore
    val aimChatID by iriStore
    val based_near by iriStore
    val birthday by iriStore
    val currentProject by iriStore
    val depiction by iriStore
    val depicts by iriStore
    val dnaChecksum by iriStore
    val familyName by iriStore
    val family_name by iriStore
    val firstName by iriStore
    val focus by iriStore
    val fundedBy by iriStore
    val geekcode by iriStore
    val gender by iriStore
    val givenName by iriStore
    val givenname by iriStore
    val holdsAccount by iriStore
    val homepage by iriStore
    val icqChatID by iriStore
    val img by iriStore
    val interest by iriStore
    val isPrimaryTopicOf by iriStore
    val jabberID by iriStore
    val knows by iriStore
    val lastName by iriStore
    val logo by iriStore
    val made by iriStore
    val maker by iriStore
    val mbox by iriStore
    val mbox_sha1sum by iriStore
    val member by iriStore
    val membershipClass by iriStore
    val msnChatID by iriStore
    val myersBriggs by iriStore
    val name by iriStore
    val nick by iriStore
    val openid by iriStore
    val page by iriStore
    val pastProject by iriStore
    val phone by iriStore
    val plan by iriStore
    val primaryTopic by iriStore
    val publications by iriStore
    val schoolHomepage by iriStore
    val sha1 by iriStore
    val skypeID by iriStore
    val status by iriStore
    val surname by iriStore
    val theme by iriStore
    val thumbnail by iriStore
    val tipjar by iriStore
    val title by iriStore
    val topic by iriStore
    val topic_interest by iriStore
    val weblog by iriStore
    val workInfoHomepage by iriStore
    val workplaceHomepage by iriStore
    val yahooChatID by iriStore
}
