package net.subroh0508.otonashi.vocabularies.foaf

import net.subroh0508.otonashi.triples.vocabulary.IriVocabulary

/*
 * This file was auto generated by otonashi-vocabularies-generator plugin
 *
 */

object FoafClass : IriVocabulary(
    "foaf",
    "Agent", "Document", "Group", "Image", "LabelProperty", "OnlineAccount", "OnlineChatAccount", "OnlineEcommerceAccount", "OnlineGamingAccount", "Organization",
    "Person", "PersonalProfileDocument", "Project"
) {
    val agent by iriStore
    val document by iriStore
    val group by iriStore
    val image by iriStore
    val labelProperty by iriStore
    val onlineAccount by iriStore
    val onlineChatAccount by iriStore
    val onlineEcommerceAccount by iriStore
    val onlineGamingAccount by iriStore
    val organization by iriStore
    val person by iriStore
    val personalProfileDocument by iriStore
    val project by iriStore
}
