package net.subroh0508.otonashi.vocabularies.imasparql

import net.subroh0508.otonashi.triples.vocabulary.IriVocabulary

/*
 * This file was auto generated by otonashi-vocabularies-generator plugin
 *
 */

object ImasparqlClass : IriVocabulary(
    "imas",
    "CallName", "Character", "CinderellaRankingResult", "Clothes", "Communication", "Event", "Facility", "Idol", "Introduction", "Live",
    "ScriptText", "SetlistNumber", "Staff", "Unit"
) {
    val callName by store
    val character by store
    val cinderellaRankingResult by store
    val clothes by store
    val communication by store
    val event by store
    val facility by store
    val idol by store
    val introduction by store
    val live by store
    val scriptText by store
    val setlistNumber by store
    val staff by store
    val unit by store
}
