package net.subroh0508.otonashi.vocabularies.imasparql

import net.subroh0508.otonashi.triples.vocabulary.IriVocabulary

/*
 * This file was auto generated by otonashi-vocabularies-generator plugin
 *
 */

object ImasparqlClass : IriVocabulary(
    "imas",
    "CallName", "Character", "CinderellaRankingResult", "Clothes", "Communication", "Event", "Facility", "Idol", "Introduction", "Live",
    "ScriptText", "SetlistNumber", "Staff", "Unit"
) {
    val callName by iriStore
    val character by iriStore
    val cinderellaRankingResult by iriStore
    val clothes by iriStore
    val communication by iriStore
    val event by iriStore
    val facility by iriStore
    val idol by iriStore
    val introduction by iriStore
    val live by iriStore
    val scriptText by iriStore
    val setlistNumber by iriStore
    val staff by iriStore
    val unit by iriStore
}
