package net.subroh0508.otonashi.vocabularies.imasparql

import net.subroh0508.otonashi.triples.Prefix

/*
 * This file was auto generated by otonashi-vocabularies-generator plugin
 *
 */

enum class ImasparqlPrefix(
    override val prefix: String,
    override val iri: String
) : Prefix {
    IMAS("imas", "<https://sparql.crssnky.xyz/imasrdf/URIs/imas-schema.ttl#>"),
    IMASRDF("imasrdf", "<https://sparql.crssnky.xyz/imasrdf/RDFs/detail/>");

    override fun toString() = "PREFIX $prefix: $iri"
}
