package net.subroh0508.otonashi.vocabularies.imasparql

import net.subroh0508.otonashi.triples.vocabulary.IriVocabulary

/*
 * This file was auto generated by otonashi-vocabularies-generator plugin
 *
 */

object ImasparqlProperty : IriVocabulary(
    "imas",
    "Attribute", "BloodType", "Bust", "Called", "Category", "Color", "Constellation", "Destination", "Division", "Favorite",
    "Handedness", "Hip", "Hobby", "NumPerformance", "NumPerformanceEncore", "Performance", "Script", "ScriptNumber", "ShoeSize", "Source",
    "SpeakerLabel", "Talent", "Title", "TuneNumber", "Type", "VoteNumber", "Waist", "Whose", "alternateNameKana", "cv",
    "familyNameKana", "givenNameKana", "nameKana"
) {
    val attribute by store
    val bloodType by store
    val bust by store
    val called by store
    val category by store
    val color by store
    val constellation by store
    val destination by store
    val division by store
    val favorite by store
    val handedness by store
    val hip by store
    val hobby by store
    val numPerformance by store
    val numPerformanceEncore by store
    val performance by store
    val script by store
    val scriptNumber by store
    val shoeSize by store
    val source by store
    val speakerLabel by store
    val talent by store
    val title by store
    val tuneNumber by store
    val type by store
    val voteNumber by store
    val waist by store
    val whose by store
    val alternateNameKana by store
    val cv by store
    val familyNameKana by store
    val givenNameKana by store
    val nameKana by store
}
