package net.subroh0508.otonashi.vocabularies.imasparql

import net.subroh0508.otonashi.triples.vocabulary.IriVocabulary

/*
 * This file was auto generated by otonashi-vocabularies-generator plugin
 *
 */

object ImasparqlProperty : IriVocabulary(
    "imas",
    "Attribute", "BloodType", "Bust", "Called", "Category", "Color", "Constellation", "Destination", "Division", "Favorite",
    "Handedness", "Hip", "Hobby", "NumPerformance", "NumPerformanceEncore", "Performance", "Script", "ScriptNumber", "ShoeSize", "Source",
    "SpeakerLabel", "Talent", "Title", "TuneNumber", "Type", "VoteNumber", "Waist", "Whose", "alternateNameKana", "cv",
    "familyNameKana", "givenNameKana", "nameKana"
) {
    val attribute by iriStore
    val bloodType by iriStore
    val bust by iriStore
    val called by iriStore
    val category by iriStore
    val color by iriStore
    val constellation by iriStore
    val destination by iriStore
    val division by iriStore
    val favorite by iriStore
    val handedness by iriStore
    val hip by iriStore
    val hobby by iriStore
    val numPerformance by iriStore
    val numPerformanceEncore by iriStore
    val performance by iriStore
    val script by iriStore
    val scriptNumber by iriStore
    val shoeSize by iriStore
    val source by iriStore
    val speakerLabel by iriStore
    val talent by iriStore
    val title by iriStore
    val tuneNumber by iriStore
    val type by iriStore
    val voteNumber by iriStore
    val waist by iriStore
    val whose by iriStore
    val alternateNameKana by iriStore
    val cv by iriStore
    val familyNameKana by iriStore
    val givenNameKana by iriStore
    val nameKana by iriStore
}
