package net.subroh0508.otonashi.core.vocabulary.common

import net.subroh0508.otonashi.triples.vocabulary.IriVocabulary

/*
 * This file was auto generated by otonashi-vocabularies-generator plugin
 *
 */

object RDFClass : IriVocabulary(
    "rdf",
    "Alt", "Bag", "List", "Property", "Seq", "Statement"
) {
    val alt by iriStore
    val bag by iriStore
    val list by iriStore
    val property by iriStore
    val seq by iriStore
    val statement by iriStore
}
