package net.subroh0508.otonashi.core.vocabulary.common

import net.subroh0508.otonashi.triples.vocabulary.IriVocabulary

/*
 * This file was auto generated by otonashi-vocabularies-generator plugin
 *
 */

object RdfProperty : IriVocabulary(
    "rdf",
    "first", "object", "predicate", "rest", "subject", "type", "value"
) {
    val first by iriStore
    val `object` by iriStore
    val predicate by iriStore
    val rest by iriStore
    val subject by iriStore
    val type by iriStore
    val value by iriStore
}
