package net.subroh0508.otonashi.core.vocabulary.common

import net.subroh0508.otonashi.triples.vocabulary.IriVocabulary

/*
 * This file was auto generated by otonashi-vocabularies-generator plugin
 *
 */

object RdfsProperty : IriVocabulary(
    "rdfs",
    "comment", "domain", "isDefinedBy", "label", "member", "range", "seeAlso", "subClassOf", "subPropertyOf"
) {
    val comment by iriStore
    val domain by iriStore
    val isDefinedBy by iriStore
    val label by iriStore
    val member by iriStore
    val range by iriStore
    val seeAlso by iriStore
    val subClassOf by iriStore
    val subPropertyOf by iriStore
}
